"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "@tanstack/react-form";
import { z } from "zod";
import { BriefcaseBusiness, KeyRound, Shield, UserRound } from "lucide-react";
import { api } from "@/lib/api";
import { useAuthStore } from "@/store/auth";
import { Button, Card } from "@/components/ui";
import { ThemeToggle } from "@/components/theme-toggle";
import { markSession } from "@/lib/session";

const schema = z.object({ email: z.string().trim().email("Enter a valid email"), password: z.string().min(8, "Password must be at least 8 characters").max(128, "Password must not exceed 128 characters") });
const demos = [{ role: "ADMIN", label: "Admin", email: "admin@example.com", password: "AdminPass123!", icon: Shield, destination: "/admin" }, { role: "RECRUITER", label: "Recruiter", email: "recruiter@example.com", password: "RecruiterPass123!", icon: BriefcaseBusiness, destination: "/recruiter" }, { role: "CANDIDATE", label: "Candidate", email: "candidate@example.com", password: "CandidatePass123!", icon: UserRound, destination: "/dashboard" }] as const;
export default function Login() { const router = useRouter(); const setUser = useAuthStore((s) => s.setUser); const [pending, setPending] = useState(false); const [error, setError] = useState(""); const [credentials, setCredentials] = useState({ email: "", password: "" }); const form = useForm({ defaultValues: credentials, onSubmit: async () => { const parsed = schema.safeParse(credentials); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Check your details"); return; } await authenticate(parsed.data.email, parsed.data.password); } });
  async function authenticate(email: string, password: string) { setPending(true); setError(""); try { const response = await api.post<{ user?: import("@/lib/types").User }>("/auth/login", { email, password }); const profile = response.user; if (!profile) throw new Error("The API did not return a user profile"); markSession(); setUser(profile); router.push(profile.role === "ADMIN" ? "/admin" : profile.role === "RECRUITER" ? "/recruiter" : "/dashboard"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to sign in"); } finally { setPending(false); } }
  return <main className="grid min-h-screen place-items-center bg-[#07111f] p-6"><div className="w-full max-w-5xl"><div className="mb-8 text-center"><div className="mx-auto grid size-12 place-items-center rounded-2xl bg-cyan-400 text-xl font-black text-slate-950">A</div><h1 className="mt-5 text-3xl font-black text-white">Welcome back</h1><p className="mt-2 text-slate-400">Sign in to your assessment workspace.</p></div><div className="grid gap-5 lg:grid-cols-[1fr_1.2fr]"><Card><form onSubmit={(e) => { e.preventDefault(); void form.handleSubmit(); }} className="space-y-5"><label className="block text-sm font-semibold text-slate-200">Email<input name="email" autoComplete="email" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-400" value={credentials.email} onChange={(e) => setCredentials({ ...credentials, email: e.target.value })} /></label><label className="block text-sm font-semibold text-slate-200">Password<input name="password" autoComplete="current-password" type="password" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-400" value={credentials.password} onChange={(e) => setCredentials({ ...credentials, password: e.target.value })} /></label>{error && <p className="text-sm text-rose-300">{error}</p>}<Button disabled={pending} className="w-full">{pending ? "Signing in…" : <><KeyRound className="mr-2 size-4" /> Sign in</>}</Button></form><p className="mt-6 text-center text-sm text-slate-500">No account? <a className="text-cyan-300" href="/register">Create one</a></p></Card><Card><p className="text-sm font-bold uppercase tracking-[.2em] text-cyan-300">Quick demo login</p><p className="mt-2 text-sm text-slate-400">Use seeded accounts to inspect the complete role-based experience.</p><div className="mt-6 grid gap-3">{demos.map(({ label, email, password, icon: Icon }) => <button key={label} type="button" onClick={() => void authenticate(email, password)} className="flex items-center gap-4 rounded-2xl border border-white/10 bg-white/[.03] p-4 text-left transition hover:border-cyan-300/50 hover:bg-cyan-300/5"><span className="grid size-11 place-items-center rounded-xl bg-cyan-400/10 text-cyan-300"><Icon className="size-5" /></span><span><span className="block font-bold text-white">{label} demo</span><span className="text-xs text-slate-500">{email}</span></span><span className="ml-auto text-cyan-300">→</span></button>)}</div></Card></div></div></main>; }
