"use client";

import Link from "next/link";
import { useParams, useRouter, useSearchParams } from "next/navigation";
import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { api, ApiError } from "@/lib/api";
import { queries } from "@/lib/queries";
import { Badge, Button, Card, EmptyState, PaginationControls, Skeleton } from "@/components/ui";
import { PageIntro } from "@/components/dashboard";

export default function InviteCandidate() {
  const { id: candidateId } = useParams<{ id: string }>(); const router = useRouter(); const searchParams = useSearchParams();
  const search = searchParams.get("search") ?? ""; const page = Number(searchParams.get("page") ?? 1); const [selected, setSelected] = useState<string[]>([]); const [pending, setPending] = useState(false);
  const candidate = useQuery({ queryKey: ["candidate", candidateId], queryFn: () => queries.candidate(candidateId) });
  const assessments = useQuery({ queryKey: ["published-assessments", page, search], queryFn: () => queries.assessments(`?page=${page}&limit=10&status=PUBLISHED${search ? `&search=${encodeURIComponent(search)}` : ""}`) });
  function toggle(id: string) { setSelected((current) => { if (current.includes(id)) return current.filter((item) => item !== id); if (current.length >= 2) { toast.error("You can invite a candidate to at most two assessments at once."); return current; } return [...current, id]; }); }
  async function invite() { if (!selected.length) { toast.error("Select at least one published assessment"); return; } setPending(true); try { const results = await Promise.allSettled(selected.map((assessmentId) => api.post(`/assessments/${assessmentId}/invitations`, { candidateId }))); const failures = results.filter((result) => result.status === "rejected"); const duplicate = failures.some((result) => result.status === "rejected" && result.reason instanceof ApiError && result.reason.status === 409 && result.reason.message.toLowerCase().includes("already exists")); if (duplicate) toast.error("You already invited this candidate for this assessment once."); else if (failures.length) toast.error(`${failures.length} invitation${failures.length === 1 ? "" : "s"} could not be sent`); if (failures.length < results.length) { toast.success(`${results.length - failures.length} invitation${results.length - failures.length === 1 ? "" : "s"} sent`); router.push(`/recruiter/candidates/${candidateId}`); } } finally { setPending(false); } }
  if (candidate.isLoading) return <Skeleton className="h-96" />; if (!candidate.data) return <EmptyState title="Candidate not found" description="This candidate is no longer available." />;
  return <div className="max-w-4xl"><PageIntro eyebrow="Recruiter workspace" title={`Invite ${candidate.data.name}`} description="Select one or more published assessments to send to this candidate." /><div className="mt-6 flex items-center gap-3"><Badge tone="success">{candidate.data.email}</Badge><Link className="text-sm text-cyan-300" href={`/recruiter/candidates/${candidateId}`}>Back to profile</Link></div><form className="mt-8" onSubmit={(event) => { event.preventDefault(); const value = new FormData(event.currentTarget).get("search")?.toString() ?? ""; router.push(`/recruiter/candidates/${candidateId}/invite?${value ? `search=${encodeURIComponent(value)}` : ""}`); }}><input name="search" defaultValue={search} placeholder="Search published assessments…" className="w-full rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-white" /></form><Card className="mt-5 p-0"><div className="divide-y divide-white/10">{assessments.isLoading ? [1, 2, 3].map((item) => <Skeleton key={item} className="m-5 h-20" />) : assessments.data?.items.length ? assessments.data.items.map((assessment) => <label key={assessment.id} className="flex cursor-pointer items-start gap-4 p-5 hover:bg-white/[.04]"><input type="checkbox" checked={selected.includes(assessment.id)} onChange={() => toggle(assessment.id)} className="mt-1 size-4 accent-cyan-400" /><span><span className="block font-semibold text-white">{assessment.title}</span><span className="mt-1 block text-sm text-slate-400">{assessment.description}</span><span className="mt-2 block text-xs text-slate-500">{assessment.itemCount ?? 0} questions · {assessment.durationMinutes} minutes</span></span></label>) : <div className="p-5"><EmptyState title="No published assessments" description="Publish an assessment before inviting candidates." /></div>}<PaginationControls page={assessments.data?.pagination.page ?? page} totalPages={assessments.data?.pagination.totalPages ?? 0} onPage={(next) => router.push(`/recruiter/candidates/${candidateId}/invite?page=${next}${search ? `&search=${encodeURIComponent(search)}` : ""}`)} /></div></Card><div className="mt-5 flex justify-end gap-3"><Button type="button" variant="secondary" onClick={() => router.push(`/recruiter/candidates/${candidateId}`)}>Cancel</Button><Button type="button" disabled={pending} onClick={() => void invite()}>Proceed to invite{selected.length ? ` (${selected.length})` : ""}</Button></div></div>;
}
