"use client";

import { useParams, useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { queries } from "@/lib/queries";
import { Button, Card, EmptyState, Skeleton } from "@/components/ui";

function formatTime(seconds: number) { const minutes = Math.floor(seconds / 60); return `${String(minutes).padStart(2, "0")}:${String(seconds % 60).padStart(2, "0")}`; }

export default function AttemptPage() {
  const { id } = useParams<{ id: string }>(); const router = useRouter(); const [answers, setAnswers] = useState<Record<string, string>>({}); const [remaining, setRemaining] = useState<number | null>(null); const [pending, setPending] = useState(false); const completed = useRef(false); const hydrated = useRef(false); const answersRef = useRef(answers); answersRef.current = answers;
  const { data, isLoading } = useQuery({ queryKey: ["attempt", id], queryFn: () => queries.attempt(id), refetchInterval: 30_000 });
  // The query response is the external source of truth used to hydrate the form once.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { if (!data) return; if (!hydrated.current) { const restored = Object.fromEntries((data.answers ?? []).map((answer) => [answer.assessmentItemId, answer.answer])); setAnswers(restored); hydrated.current = true; } setRemaining(data.deadline ? Math.max(0, Math.ceil((new Date(data.deadline).getTime() - Date.now()) / 1000)) : data.remainingTimeSeconds ?? null); }, [data]);
  const cancelInBackground = () => { if (completed.current) return; const body = JSON.stringify({ answers: Object.entries(answersRef.current).map(([assessmentItemId, answer]) => ({ assessmentItemId, answer })) }); if (typeof navigator !== "undefined" && navigator.sendBeacon) { navigator.sendBeacon(`/api/backend/attempts/${id}/cancel`, new Blob([body], { type: "application/json" })); } else { void api.post(`/attempts/${id}/cancel`, JSON.parse(body)); } };
  useEffect(() => { const leave = () => cancelInBackground(); window.addEventListener("beforeunload", leave); return () => { window.removeEventListener("beforeunload", leave); leave(); }; }, [id]);
  useEffect(() => { if (remaining === null || remaining <= 0) return; const timer = window.setInterval(() => setRemaining((value) => value === null ? value : Math.max(0, value - 1)), 1000); return () => window.clearInterval(timer); }, [remaining]);
  useEffect(() => { if (remaining !== 0 || !data || pending || completed.current) return; toast.info("Time is up. Submitting your assessment."); void submit(); }, [remaining]);
  if (isLoading) return <Skeleton className="h-96" />; const assessment = data?.assessment; if (!data || !assessment?.items) return <EmptyState title="Attempt unavailable" description="This attempt may have expired or already been submitted." />; const items = assessment.items;
  async function submit() { setPending(true); try { completed.current = true; await api.post(`/attempts/${id}/submit`, { answers: items.map((item) => ({ assessmentItemId: item.id, answer: answersRef.current[item.id] ?? "" })) }); toast.success("Assessment submitted"); router.push("/dashboard"); } catch (cause) { completed.current = false; toast.error(cause instanceof Error ? cause.message : "Unable to submit assessment"); } finally { setPending(false); } }
  async function cancel() { if (!window.confirm("Cancel this attempt? Your current answers will be saved and the attempt will be marked cancelled.")) return; setPending(true); try { completed.current = true; await api.post(`/attempts/${id}/cancel`, { answers: Object.entries(answersRef.current).map(([assessmentItemId, answer]) => ({ assessmentItemId, answer })) }); toast.success("Attempt cancelled"); router.push("/dashboard"); } catch (cause) { completed.current = false; toast.error(cause instanceof Error ? cause.message : "Unable to cancel attempt"); } finally { setPending(false); } }
  return <div className="mx-auto max-w-3xl"><div className="sticky top-0 z-10 -mx-5 mb-6 border-b border-white/10 bg-[#07111f]/95 px-5 py-4 backdrop-blur lg:-mx-10 lg:px-10"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-cyan-300">Active attempt</p><h1 className="mt-2 text-2xl font-black text-white">{assessment.title}</h1><p className="mt-1 text-xs text-slate-500">Duration: {assessment.durationMinutes} minutes</p></div><div className={`rounded-xl px-4 py-3 text-xl font-black ${remaining !== null && remaining < 60 ? "bg-rose-400/15 text-rose-300" : "bg-cyan-400/10 text-cyan-300"}`} aria-live="polite">{remaining === null ? "Timed" : formatTime(remaining)}</div></div></div><div className="space-y-4">{items.map((item, index) => <Card key={item.id}><p className="text-sm font-bold text-cyan-300">Question {index + 1} · {item.points} pts</p><h2 className="mt-3 font-bold text-white">{item.question}</h2>{item.type === "MCQ" ? <div className="mt-5 grid gap-2">{item.options.map((option) => <label key={option} className="flex cursor-pointer items-center gap-3 rounded-xl border border-white/10 p-3 text-sm text-slate-300 hover:border-cyan-300/50"><input type="radio" name={item.id} value={option} checked={answers[item.id] === option} onChange={(event) => setAnswers((current) => ({ ...current, [item.id]: event.target.value }))} />{option}</label>)}</div> : <textarea rows={5} className="mt-5 w-full rounded-xl border border-white/10 bg-black/20 p-4 text-white" value={answers[item.id] ?? ""} onChange={(event) => setAnswers((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="Write your answer…" />}</Card>)}</div><div className="mt-6 flex flex-wrap justify-end gap-3"><Button type="button" variant="secondary" disabled={pending} onClick={() => void cancel()}>Cancel attempt</Button><Button disabled={pending} onClick={() => void submit()}>{pending ? "Saving…" : "Submit assessment"}</Button></div></div>;
}
