"use client";

import { useParams, useRouter } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { queries } from "@/lib/queries";
import { Badge, Button, Card, EmptyState, Skeleton } from "@/components/ui";
import { PageIntro } from "@/components/dashboard";

export default function CandidateResultDetails() { const { id } = useParams<{ id: string }>(); const router = useRouter(); const { data, isLoading, error } = useQuery({ queryKey: ["candidate-result", id], queryFn: () => queries.attempt(id) }); if (isLoading) return <Skeleton className="h-96" />; if (error || !data) return <EmptyState title="Result unavailable" description={error instanceof Error ? error.message : "This result could not be loaded."} />; const result = data.result; const evaluated = data.status === "EVALUATED" && result; return <div className="max-w-3xl"><PageIntro eyebrow="Candidate workspace" title={data.assessment?.title ?? "Assessment result"} description={data.assessment?.description ?? "Assessment details and evaluation result."} /><Card className="mt-8"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-slate-500">Assessment duration</p><p className="mt-1 font-semibold text-white">{data.assessment?.durationMinutes ?? "—"} minutes</p></div><Badge tone={evaluated ? (result.passed ? "success" : "danger") : "warning"}>{evaluated ? (result.passed ? "PASSED" : "FAILED") : data.status.replace("_", " ")}</Badge></div>{evaluated ? <div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="rounded-xl bg-white/[.04] p-4"><p className="text-xs text-slate-500">Marks</p><p className="mt-2 text-2xl font-black text-white">{result.totalScore}/{result.maxScore}</p></div><div className="rounded-xl bg-white/[.04] p-4"><p className="text-xs text-slate-500">Percentage</p><p className="mt-2 text-2xl font-black text-white">{result.percentage}%</p></div><div className="rounded-xl bg-white/[.04] p-4"><p className="text-xs text-slate-500">Passing score</p><p className="mt-2 text-2xl font-black text-white">{result.passingScore}%</p></div></div> : <p className="mt-8 rounded-xl bg-amber-400/10 p-4 text-sm text-amber-100">This attempt is submitted and may still require manual written-answer evaluation.</p>}<Button type="button" variant="secondary" className="mt-8" onClick={() => router.push("/dashboard/payments")}>Back to results</Button></Card></div>; }
