"use client";
import { useSearchParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { queries } from "@/lib/queries";
import { Badge, Card, EmptyState, Skeleton } from "@/components/ui";
import { PageIntro } from "./dashboard";
import type { User } from "@/lib/types";
export function AdminUsers() { const search = useSearchParams().get("search") ?? ""; const { data, isLoading } = useQuery({ queryKey: ["admin-users", search], queryFn: () => queries.adminUsers(`?page=1&limit=30${search ? `&search=${encodeURIComponent(search)}` : ""}`) }); return <><PageIntro eyebrow="Platform control" title="User directory" description="Search, inspect, and manage the people who use Atlas." /><form className="mt-8"><input name="search" defaultValue={search} placeholder="Search by name or email…" className="w-full rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-white" /></form><Card className="mt-5 p-0"><div className="divide-y divide-white/10">{isLoading ? [1, 2, 3].map((i) => <Skeleton className="m-5 h-16" key={i} />) : data?.items.length ? data.items.map((user: User) => <div className="flex flex-col gap-2 p-5 sm:flex-row sm:items-center sm:justify-between" key={user.id}><div><p className="font-semibold text-white">{user.name}</p><p className="text-sm text-slate-500">{user.email}</p></div><div className="flex gap-2"><Badge>{user.role}</Badge><Badge tone={user.status === "ACTIVE" ? "success" : "danger"}>{user.status}</Badge></div></div>) : <div className="p-5"><EmptyState title="No users found" description="Try a different search." /></div>}</div></Card></>; }
export function AdminApplications() { const { data, isLoading } = useQuery({ queryKey: ["applications"], queryFn: () => queries.applications("?page=1&limit=30") }); return <><PageIntro eyebrow="Platform control" title="Recruiter applications" description="Review pending recruiting teams before granting authoring access." /><Card className="mt-8 p-0"><div className="divide-y divide-white/10">{isLoading ? <Skeleton className="m-5 h-16" /> : data?.items.length ? data.items.map((user: User) => <div className="flex items-center justify-between p-5" key={user.id}><div><p className="font-semibold text-white">{user.name}</p><p className="text-sm text-slate-500">{user.email}</p></div><Badge tone="warning">PENDING</Badge></div>) : <div className="p-5"><EmptyState title="No pending applications" description="New recruiter requests will appear here." /></div>}</div></Card></>; }
export function AuditLogs() { const { data, isLoading } = useQuery({ queryKey: ["audit-logs"], queryFn: () => queries.auditLogs("?page=1&limit=30") }); return <><PageIntro eyebrow="Platform control" title="Audit logs" description="Read-only activity records for sensitive platform operations." /><Card className="mt-8"><div className="space-y-3">{isLoading ? <Skeleton className="h-20" /> : data?.items.length ? data.items.map((log, index) => <div className="rounded-xl bg-white/[.03] p-4" key={String(log.id ?? index)}><p className="font-semibold text-white">{String(log.action ?? "Platform activity")}</p><p className="mt-1 text-xs text-slate-500">{String(log.entity ?? "—")} · {String(log.createdAt ?? "")}</p></div>) : <EmptyState title="No audit records" description="There is no recorded activity for this view." />}</div></Card></>; }
