"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useForm } from "@tanstack/react-form";
import { z } from "zod";
import { api } from "@/lib/api";
import { Button, Card } from "@/components/ui";
import { PageIntro } from "./dashboard";

const input = "mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white outline-none focus:border-cyan-400";
export function ProblemForm() { const router = useRouter(); const [error, setError] = useState(""); const form = useForm({ defaultValues: { title: "", question: "", type: "MCQ" as "MCQ" | "WRITTEN", options: "", correctAnswer: "", expectedAnswer: "", points: 1 }, onSubmit: async ({ value }) => { const payload = value.type === "MCQ" ? { ...value, options: value.options.split("\n").map((option) => option.trim()).filter(Boolean), points: Number(value.points) } : { title: value.title, question: value.question, type: value.type, expectedAnswer: value.expectedAnswer, points: Number(value.points) }; const parsed = z.object({ title: z.string().min(3), question: z.string().min(5), points: z.number().min(1) }).safeParse(payload); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Check the form"); return; } try { await api.post("/problems", payload); router.push("/recruiter/problems"); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create problem"); } } }); return <div className="max-w-3xl"><PageIntro eyebrow="Problem bank" title="Create a problem" description="Use a focused prompt that measures a real engineering skill." /><Card className="mt-8"><form className="space-y-5" onSubmit={(e) => { e.preventDefault(); void form.handleSubmit(); }}><Field label="Title" value={form.getFieldValue("title")} onChange={(v) => form.setFieldValue("title", v)} /><Field label="Question" value={form.getFieldValue("question")} onChange={(v) => form.setFieldValue("question", v)} area /><label className="block text-sm font-semibold">Question type<select className={input} value={form.getFieldValue("type")} onChange={(e) => form.setFieldValue("type", e.target.value as "MCQ" | "WRITTEN")}><option value="MCQ">Multiple choice</option><option value="WRITTEN">Written answer</option></select></label>{form.getFieldValue("type") === "MCQ" ? <><Field label="Options (one per line)" value={form.getFieldValue("options")} onChange={(v) => form.setFieldValue("options", v)} area /><Field label="Correct answer" value={form.getFieldValue("correctAnswer")} onChange={(v) => form.setFieldValue("correctAnswer", v)} /></> : <Field label="Expected answer" value={form.getFieldValue("expectedAnswer")} onChange={(v) => form.setFieldValue("expectedAnswer", v)} area />}<label className="block text-sm font-semibold">Points<input type="number" className={input} value={form.getFieldValue("points")} onChange={(e) => form.setFieldValue("points", Number(e.target.value))} /></label>{error && <p className="text-sm text-rose-300">{error}</p>}<Button>Save problem</Button></form></Card></div>; }
export function AssessmentForm() { const router = useRouter(); const [error, setError] = useState(""); const form = useForm({ defaultValues: { title: "", description: "", durationMinutes: 60, passingScore: 60 }, onSubmit: async ({ value }) => { try { const assessment = await api.post<{ id: string }>("/assessments", { ...value, durationMinutes: Number(value.durationMinutes), passingScore: Number(value.passingScore) }); router.push(`/recruiter/assessments/${assessment.id}`); } catch (e) { setError(e instanceof Error ? e.message : "Unable to create assessment"); } } }); return <div className="max-w-3xl"><PageIntro eyebrow="Assessment authoring" title="Create an assessment" description="Start with metadata, then add ordered questions from your problem bank." /><Card className="mt-8"><form className="space-y-5" onSubmit={(e) => { e.preventDefault(); void form.handleSubmit(); }}><Field label="Assessment title" value={form.getFieldValue("title")} onChange={(v) => form.setFieldValue("title", v)} /><Field label="Description" value={form.getFieldValue("description")} onChange={(v) => form.setFieldValue("description", v)} area /><div className="grid gap-4 sm:grid-cols-2"><Field label="Duration (minutes)" value={String(form.getFieldValue("durationMinutes"))} onChange={(v) => form.setFieldValue("durationMinutes", Number(v))} type="number" /><Field label="Passing score (%)" value={String(form.getFieldValue("passingScore"))} onChange={(v) => form.setFieldValue("passingScore", Number(v))} type="number" /></div>{error && <p className="text-sm text-rose-300">{error}</p>}<Button>Create draft</Button></form></Card></div>; }
function Field({ label, value, onChange, area, type = "text" }: { label: string; value: string; onChange: (value: string) => void; area?: boolean; type?: string }) { return <label className="block text-sm font-semibold">{label}{area ? <textarea rows={4} className={input} value={value} onChange={(e) => onChange(e.target.value)} /> : <input type={type} className={input} value={value} onChange={(e) => onChange(e.target.value)} />}</label>; }
