"use client";
import { useQuery } from "@tanstack/react-query";
import { queries } from "@/lib/queries";
import { api } from "@/lib/api";
import { Badge, Button, Card, EmptyState, Skeleton } from "@/components/ui";
import { PageIntro } from "./dashboard";
export function InvitationsPage() { const { data, isLoading } = useQuery({ queryKey: ["invitations"], queryFn: () => queries.invitations("?page=1&limit=30") }); return <><PageIntro eyebrow="Candidate workspace" title="Invitations" description="Accept an invitation to unlock your next assessment attempt." /><Card className="mt-8 p-0"><div className="divide-y divide-white/10">{isLoading ? <Skeleton className="m-5 h-20" /> : data?.items.length ? data.items.map((invite) => <div className="flex items-center justify-between gap-4 p-5" key={String(invite.id)}><div><p className="font-semibold text-white">{String(invite.assessmentTitle ?? "Technical assessment")}</p><p className="mt-1 text-sm text-slate-500">{String(invite.recruiterName ?? "Recruiting team")}</p></div><Badge tone="warning">{String(invite.status ?? "PENDING")}</Badge></div>) : <div className="p-5"><EmptyState title="No invitations yet" description="When a recruiter invites you, the assessment will appear here." /></div>}</div></Card></>; }
export function CandidateProfile() { const { data, isLoading } = useQuery({ queryKey: ["me"], queryFn: queries.me }); if (isLoading) return <Skeleton className="h-80" />; return <><PageIntro eyebrow="Candidate workspace" title="Profile & settings" description="Keep your account details up to date." /><Card className="mt-8 max-w-2xl"><p className="text-sm text-slate-400">Name</p><p className="mt-1 text-xl font-bold text-white">{data?.name}</p><p className="mt-6 text-sm text-slate-400">Email</p><p className="mt-1 text-white">{data?.email}</p><Button className="mt-8" onClick={() => void api.patch("/users/me", { name: data?.name })}>Save profile</Button></Card></>; }
export function CandidatePayments() { const { data, isLoading } = useQuery({ queryKey: ["attempts-payments"], queryFn: () => queries.attempts("?page=1&limit=30") }); return <><PageIntro eyebrow="Candidate workspace" title="Results & history" description="Your evaluated assessment results live here." /><Card className="mt-8"><div className="space-y-3">{isLoading ? <Skeleton className="h-20" /> : data?.items.filter((item) => item.status === "EVALUATED").length ? data.items.filter((item) => item.status === "EVALUATED").map((attempt) => <div key={attempt.id} className="flex items-center justify-between rounded-xl bg-white/[.03] p-4"><div><p className="font-semibold text-white">{attempt.assessment?.title ?? "Assessment"}</p><p className="text-sm text-slate-500">Score: {attempt.score}/{attempt.maxScore}</p></div><Badge tone={attempt.passed ? "success" : "danger"}>{attempt.passed ? "PASSED" : "NOT PASSED"}</Badge></div>) : <EmptyState title="No evaluated results" description="Completed assessments will show results after evaluation." />}</div></Card></>; }
