"use client";

import { useRouter, useSearchParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { api } from "@/lib/api";
import { queries } from "@/lib/queries";
import { Badge, Button, Card, EmptyState, PaginationControls, Skeleton } from "@/components/ui";
import { PageIntro } from "@/components/dashboard";

type Invitation = { id: string; status: string; expiresAt?: string; assessment?: { title?: string; description?: string; durationMinutes?: number; recruiter?: { name?: string; recruiterProfile?: { companyName?: string | null } | null } } };

export function CandidateInvitations() { const router = useRouter(); const searchParams = useSearchParams(); const page = Number(searchParams.get("page") ?? 1); const { data, isLoading, refetch } = useQuery({ queryKey: ["invitations", page], queryFn: () => queries.invitations(`?page=${page}&limit=10`) }); async function acceptAndStart(invitation: Invitation) { try { const accepted = await api.post<{ token: string }>(`/invitations/id/${invitation.id}/accept`); toast.success("Invitation accepted"); const attempt = await api.post<{ id: string }>(`/invitations/${accepted.token}/start`); toast.success("Assessment started"); router.push(`/attempt/${attempt.id}`); } catch (cause) { toast.error(cause instanceof Error ? cause.message : "Unable to start assessment"); await refetch(); } } return <><PageIntro eyebrow="Candidate workspace" title="Invitations" description="Accept an invitation to start your next timed assessment." /><Card className="mt-8 p-0"><div className="divide-y divide-white/10">{isLoading ? [1, 2, 3].map((item) => <Skeleton key={item} className="m-5 h-24" />) : data?.items.length ? data.items.map((raw) => { const invite = raw as Invitation; const assessment = invite.assessment; const company = assessment?.recruiter?.recruiterProfile?.companyName ?? assessment?.recruiter?.name ?? "Recruiting team"; return <div className="flex flex-col gap-4 p-5 sm:flex-row sm:items-center sm:justify-between" key={invite.id}><div><p className="font-semibold text-white">{assessment?.title ?? "Technical assessment"}</p><p className="mt-1 text-sm text-slate-500">{company} · {assessment?.durationMinutes ?? "—"} minutes</p><p className="mt-1 text-xs text-slate-500">Expires {invite.expiresAt ? new Date(invite.expiresAt).toLocaleString() : "—"}</p></div><div className="flex items-center gap-3"><Badge tone={invite.status === "PENDING" ? "warning" : "success"}>{invite.status}</Badge>{invite.status === "PENDING" && <Button type="button" onClick={() => void acceptAndStart(invite)}>Accept & start</Button>}</div></div>; }) : <div className="p-5"><EmptyState title="No invitations yet" description="When a recruiter invites you, the assessment will appear here." /></div>}<PaginationControls page={data?.pagination.page ?? page} totalPages={data?.pagination.totalPages ?? 0} onPage={(next) => router.push(`/dashboard/invitations?page=${next}`)} /></div></Card></>; }
