"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { Plus, Search } from "lucide-react";
import { queries } from "@/lib/queries";
import { Badge, Button, Card, EmptyState, Skeleton } from "@/components/ui";
import { PageIntro } from "./dashboard";
import type { Assessment, Problem } from "@/lib/types";

export function ProblemList() { const params = useSearchParams(); const search = params.get("search") ?? ""; const { data, isLoading } = useQuery({ queryKey: ["problems", search], queryFn: () => queries.problems(`?page=${params.get("page") ?? 1}&limit=10${search ? `&search=${encodeURIComponent(search)}` : ""}`) }); return <><PageIntro eyebrow="Recruiter workspace" title="Problem bank" description="Maintain reusable questions before assembling an assessment." /><div className="mt-8 flex flex-col gap-3 sm:flex-row"><form className="relative flex-1"><Search className="absolute left-3 top-3 size-4 text-slate-500" /><input name="search" defaultValue={search} placeholder="Search questions…" className="w-full rounded-xl border border-white/10 bg-white/[.04] py-2.5 pl-10 pr-4 text-white" /></form><Link href="/recruiter/problems/new"><Button><Plus className="mr-2 size-4" /> New problem</Button></Link></div><Card className="mt-5 p-0"><div className="divide-y divide-white/10">{isLoading ? [1, 2, 3].map((item) => <Skeleton key={item} className="m-5 h-16" />) : data?.items.length ? data.items.map((problem: Problem) => <div className="flex flex-col gap-3 p-5 sm:flex-row sm:items-center sm:justify-between" key={problem.id}><div><p className="font-semibold text-white">{problem.title}</p><p className="mt-1 line-clamp-1 text-sm text-slate-500">{problem.question}</p></div><div className="flex items-center gap-3"><Badge>{problem.type}</Badge><span className="text-sm text-slate-400">{problem.points} pts</span></div></div>) : <div className="p-5"><EmptyState title="No problems found" description="Change the search or create your first reusable question." /></div>}</div></Card></>; }
export function AssessmentList() { const params = useSearchParams(); const status = params.get("status") ?? ""; const { data, isLoading } = useQuery({ queryKey: ["assessments", status], queryFn: () => queries.assessments(`?page=1&limit=20${status ? `&status=${status}` : ""}`) }); return <><PageIntro eyebrow="Recruiter workspace" title="Assessments" description="Design, ready, publish, and monitor technical assessments." /><div className="mt-8 flex flex-wrap gap-2">{["", "DRAFT", "READY", "PUBLISHED"].map((value) => <Link key={value || "all"} href={value ? `/recruiter/assessments?status=${value}` : "/recruiter/assessments"}><Button variant={status === value ? "primary" : "secondary"}>{value || "All"}</Button></Link>)}<Link className="ml-auto" href="/recruiter/assessments/new"><Button><Plus className="mr-2 size-4" /> New assessment</Button></Link></div><div className="mt-5 grid gap-4 md:grid-cols-2">{isLoading ? [1, 2, 3, 4].map((item) => <Skeleton key={item} className="h-44" />) : data?.items.length ? data.items.map((assessment: Assessment) => <Card key={assessment.id}><div className="flex items-start justify-between gap-4"><div><p className="font-bold text-white">{assessment.title}</p><p className="mt-2 line-clamp-2 text-sm text-slate-400">{assessment.description}</p></div><Badge tone={assessment.status === "PUBLISHED" ? "success" : assessment.status === "DRAFT" ? "neutral" : "warning"}>{assessment.status}</Badge></div><div className="mt-6 flex justify-between text-xs text-slate-500"><span>{assessment.itemCount ?? 0} questions · {assessment.durationMinutes} min</span><Link className="text-cyan-300" href={`/recruiter/assessments/${assessment.id}`}>Open →</Link></div></Card>) : <EmptyState title="No assessments found" description="Start with a draft and build your first assessment." />}</div></>; }
