"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useForm } from "@tanstack/react-form";
import { z } from "zod";
import { api } from "@/lib/api";
import { Button, Card } from "@/components/ui";
const schema = z.object({ name: z.string().trim().min(2), email: z.string().trim().email(), password: z.string().min(8), role: z.enum(["CANDIDATE", "RECRUITER"]) });
export default function Register() { const router = useRouter(); const [error, setError] = useState(""); const form = useForm({ defaultValues: { name: "", email: "", password: "", role: "CANDIDATE" as "CANDIDATE" | "RECRUITER" }, onSubmit: async ({ value }) => { const parsed = schema.safeParse(value); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Check the form"); return; } try { await api.post("/auth/register", parsed.data); router.push(`/verify-email?email=${encodeURIComponent(parsed.data.email)}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to register"); } } }); const recruiter = form.getFieldValue("role") === "RECRUITER"; return <main className="grid min-h-screen place-items-center bg-[#07111f] p-6"><Card className="w-full max-w-lg"><h1 className="text-3xl font-black text-white">Create your workspace</h1><p className="mt-2 text-slate-400">Join Atlas as a candidate or recruiting team.</p><form className="mt-8 space-y-4" onSubmit={(event) => { event.preventDefault(); void form.handleSubmit(); }}><label className="block text-sm font-semibold text-slate-200">Full name<input className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white" value={form.getFieldValue("name")} onChange={(event) => form.setFieldValue("name", event.target.value)} /></label><label className="block text-sm font-semibold text-slate-200">Email<input type="email" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white" value={form.getFieldValue("email")} onChange={(event) => form.setFieldValue("email", event.target.value)} /></label><label className="block text-sm font-semibold text-slate-200">Password<input type="password" className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-white" value={form.getFieldValue("password")} onChange={(event) => form.setFieldValue("password", event.target.value)} /></label><label className="block text-sm font-semibold text-slate-200">Account type<select className="mt-2 w-full rounded-xl border border-white/10 bg-slate-900 px-4 py-3 text-white" value={form.getFieldValue("role")} onChange={(event) => form.setFieldValue("role", event.target.value as "CANDIDATE" | "RECRUITER")}><option value="CANDIDATE">Candidate</option><option value="RECRUITER">Recruiter</option></select></label>{recruiter && <div className="rounded-xl border border-amber-300/20 bg-amber-300/10 p-4 text-sm leading-6 text-amber-100"><strong>Recruiter application review</strong><br />Your application is forwarded to an admin. Your recruiter status remains pending, and you remain a candidate until an admin approves your application.</div>}{error && <p role="alert" className="text-sm text-rose-300">{error}</p>}<Button className="w-full">Continue</Button></form></Card></main>; }
